// Generated by https://quicktype.io

class Pagination {
  int totalCount;
  int pageSize;
  int currentPage;
  int totalPages;

  Pagination({
    this.totalCount,
    this.pageSize,
    this.currentPage,
    this.totalPages,
  });

  factory Pagination.fromJson(Map<String, dynamic> json) {
    return Pagination(
      totalCount: json['totalCount'],
      pageSize: json['pageSize'],
      currentPage: json['currentPage'],
      totalPages: json['totalPages']
    );
  }
}
